app/models.py
import os
from random import shuffle
from datetime import datetime
from app import app, api
from flask_restful import Resource
from flask_sqlalchemy import SQLAlchemy
from flask_marshmallow import Marshmallow
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin, LoginManager


# db file location for the server (current directory)
basedir = os.path.abspath(os.path.dirname(__file__))
# Database configs
app.secret_key = os.environ.get('SECRET_KEY')
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + os.path.join(basedir, 'cards.sqlite')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
# Init db
db = SQLAlchemy(app)
# Init Marshmallow
ma = Marshmallow(app)
# Init LoginManager
login = LoginManager()

# User Models
class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(80), unique=True, nullable=False)
    username = db.Column(db.String(80), unique=True, nullable=False)
    pw_hash = db.Column(db.String(), nullable=False)
    games = db.relationship('Match', backref='player', lazy=True)

    def set_pw(self, password):
        self.pw_hash = generate_password_hash(password)

    def check_pw(self, password):
        return check_password_hash(self.pw_hash, password)

    def __repr__(self):
        return f'User(\'{self.username}\', \'{self.email}\')'


# Link Flask_Login to db
@login.user_loader
def load_user(id):
    return User.query.get(int(id))


# Match Classes/Models
class Match(db.Model):
    """A single card game"""
    id = db.Column(db.Integer, primary_key=True, nullable=False)
    match_date = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    winner = db.Column(db.String(80))
    player_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def __repr__(self):
        return f'{self.match_date} between Dealer and {self.player_id}, won by {self.winner}'


# Cards Classes/Models
class Card:
    """Creates a single card"""
    def __init__(self, suit, value):
        self.suit = suit
        self.value = value

    def show_card(self):
        print(f'{self.value} of {self.suit.title()}')

    def get(self):
        return 

    def __repr__(self):
        return f'{self.value} of {self.suit}'


class Deck:
    def __init__(self):
        self.deck = {
            'suits': ['Clubs', 'Diamonds', 'Hearts', 'Spades'],
            'cards': {
                1: 'Ace',
                2: '2',
                3: '3',
                4: '4',
                5: '5',
                6: '6',
                7: '7',
                8: '8',
                9: '9',
                10: '10',
                11: 'Jack',
                12: 'Queen',
                13: 'King'
            }
        }
        self.deck_of_cards = []

    def build_deck(self, num_decks=1):
        deck_num = 1
        while deck_num <= num_decks:
            for suit in self.deck['suits']:
                for card in self.deck['cards']:
                    self.deck_of_cards.append(f'{card} of {suit}')
            deck_num += 1
        print(self.deck_of_cards)
        return self.deck_of_cards

    def shuffle_cards(self):
        shuffle(self.deck_of_cards)
        return self.deck_of_cards

# class Deck(Resource):
    # """Creates deck(s) of cards and shuffles"""
    
    # def __init__(self, num_decks=1):
    #     self.num_decks = num_decks
    #     self.cards = []
    #     self.suits = ['Spades', 'Diamonds', 'Clubs', 'Hearts']
    #     # self.build_deck()

    # def build_deck(self):
    #     deck_num = 1
    #     while deck_num <= self.num_decks:
    #         for suit in self.suits:
    #             for value in range(1, 14):
    #                 self.cards.append(Card(suit, str(value)))
    #         deck_num += 1

    # def shuffle_deck(self):
    #     shuffle(self.cards)
    #     # return self.cards

    # def show_cards(self):
    #     for card in self.cards:
    #         card.show_card()

    # def draw_card(self):
    #     return self.cards.pop()


# Match Schemas
class MatchSchema(ma.Schema):
    class Meta:
        model = Match


# class CardSchema(ma.Schema):
#     class Meta:
#         model = Card

class DeckSchema(ma.Schema):
    class Meta:
        model = Deck
        fields = ('deck_of_cards',)


# Initialize the schemas
match_schema = MatchSchema(many=True)
deck_schema = DeckSchema()

# API resources
# api.add_resource(Card, '/card')
# api.add_resource(Deck, '/deck')

app/__init__.py
from logging import log
from flask import Flask
from flask_restful import Api

# Init Flask app
app = Flask(__name__)
api = Api(app)

from .models import login
login.init_app(app)
login.login_view = 'login'

from app import routes
app.register_blueprint(routes.cards)
app.register_blueprint(routes.user)

app/routes.py
from app.models import User, Deck, match_schema, deck_schema
from app import app
from flask import (
    Blueprint, request, jsonify, render_template, redirect, url_for
    )
from flask_login import current_user, login_user, logout_user
from .models import db


cards = Blueprint('cards', __name__, url_prefix='/cards')
user = Blueprint('user', __name__, url_prefix='/user')

deck = Deck()

@app.route('/', methods=['GET'])
def index():
    return jsonify(
        {
            'msg': 'Hello Flask'
        }
    )


# ----------[ Cardgame Routes ]---------- #
# @cards.route('/')
# def cards_index():
#     return 'Cards home'

@cards.route('/get-deck', methods=['GET'])
def get_shuffled_deck():
    deck.build_deck()
    deck.shuffle_cards()
    output = deck_schema.dump(deck)
    return jsonify(output)

@cards.route('/blackjack/deal', methods=['GET'])
def post_blackjack():
    hand = []
    deck.build_deck()
    deck.shuffle_cards()
    for _ in range(2):
        hand.append(deck.deck_of_cards.pop())
    output = deck_schema.dump(hand)
    print(deck.deck_of_cards)
    print(hand)
    return jsonify(output)

@cards.route('/blackjack', methods=['PUT'])
def put_blackjack():
    return 'Blackjack PUT'

@cards.route('/blackjack', methods=['DELETE'])
def delete_blackjack():
    return 'Blackjack DELETE'


# ----------[ User Routes ]---------- #
@user.route('/login', methods=['POST', 'GET'])
def login():
    if current_user.is_authenticated:
        return redirect('/cards')

    if request.method == 'POST':
        email = request.form['email']
        user = User.query.filter_by(email=email).first()
        if user is not None and user.check_pw(request.form['password']):
            login_user(user)
            return redirect('/cards')

    return render_template('user/login.html')


@user.route('/register', methods=['POST', 'GET'])
def register():
    if current_user.is_authenticated:
        return redirect('/cards')

    if request.method == 'POST':
        email = request.form['email']
        username = request.form['username']
        password = request.form['password']
        user = User.query.filter_by(email=email).first()
        if user:
            return redirect(url_for('user.login'))

        new_user = User(email=email, username=username)
        new_user.set_pw(password)
        db.session.add(new_user)
        db.session.commit()
        return redirect('/user/login')
    
    return render_template('user/register.html')

@user.route('/logout')
def logout():
    logout_user()
    return render_template('user/logout.html')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <nav>
        {% if g.user %}
            <li><span>{{ g.user['username'] }}</span></li>
            <li><a href="{{ url_for('user.logout') }}">Log Out</a></li>
        {% else %}
            <li><a href="{{ url_for('user.register') }}">Register</a></li>
            <li><a href="{{ url_for('user.login') }}">Log In</a></li>
        {% endif %}
    </nav>
    <section class="container content">
        <header>
            {% block header %}{% endblock %}
        </header>
        {% for message in get_flashed_messages() %}
            <div class="flash">{{ message }}</div>
        {% endfor %}
        {% block content %}{% endblock %}
    </section>
    <footer>
        {% include 'partials/_footer.html' %}
    </footer>
</body>
</html>

app/templates/partials/_footer.html
&copy; Richard Sandrok

app/templates/user/login.html
{% extends 'base.html' %}

{% block header %}
    <h2>{% block title %}Log In{% endblock %}</h2>
{% endblock %}

{% block content %}
    <form method="post">
        <label for="email">Email</label>
        <input type="email" name="email" id="email" required>
        <label for="password">Password</label>
        <input type="password" name="password" id="password" required>
        <input type="submit" value="Log In">
    </form>
    <h3>Don't have an account?</h3>
    <h4><a href="{{ url_for('user.register') }}">Register here</a></h4>
{% endblock %}

app/templates/user/logout.html
{% extends 'base.html' %}

{% block header %}
    <h2>{% block title %}Log Out{% endblock %}</h2>
{% endblock %}

{% block content %}
    <p>Bye!</p>
{% endblock %}

app/templates/user/register.html
{% extends 'base.html' %}

{% block header %}
    <h2>{% block title %}Register{% endblock %}</h2>
{% endblock %}

{% block content %}
    <form action="" method="post">
        <label for="email">Email</label>
        <input type="email" name="email" id="email" required>
        <label for="username">Username</label>
        <input type="username" name="username" id="username" required>
        <label for="password">Password</label>
        <input type="password" name="password" id="password" required>
        <input type="submit" value="Register">
    </form>
    <h3>Got an account already?</h3>
    <h4><a href="{{ url_for('user.login') }}">Log In</a></h4>
{% endblock %}